RUN_NAME: 'imagenet100_usl-t_0.3'

SKIP_SAVE: False
RECOMPUTE_ALL: True
RECOMPUTE_NUM_DEP: True

DATASET:
  NAME: 'imagenet100'
  TRANSFORM_NAME: 'imagenet100'
  ROOT_DIR: '../data/ImageNet100'

DATALOADER:
  WORKERS: 16
  BATCH_SIZE: 512

MODEL:
  ARCH: 'resnet50'
  PRETRAIN_PATH: '../usl-t_pretraining/saved/imagenet100_feat_v5/checkpoint.pth'
  BACKBONE_DIM: 2048

USLT:
  NUM_SELECTED_SAMPLES: 400
  USE_MEAN_PROB: False
  NUM_CLUSTERS: 400

